version: '2'
services:
  app:
    image: microsoft/aspnet:1.0.0-rc1-update1-coreclr
    working_dir: /app
    command: bash -c "dnu restore && dnx web"
    volumes:
      - ./HelloMVC:/app
    ports:
      - "5004:5004"
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_USER: aspnet
      POSTGRES_PASSWORD: aspnet

  mon:
    image: prom/prometheus
    volumes:
      - ./mon/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  elk:
    image: willdurand/elk
    ports:
        - "8080:80"
    volumes:
        - ./elk/config:/etc/logstash

  registry:
    image: registry:2
    ports:
      - '5000:5000'

  gocd-server:
    image: gocd/gocd-server
    ports:
      - '8153:8153'
    volumes:
      - ./gocd/var/lib/go-server/addons:/var/lib/go-server/addons
      - ./gocd/var/log/go-server:/var/log/go-server
      - ./gocd/etc/go:/etc/go
      - ./gocd/go-addons:/go-addons
      - ./gocd/var/go:/var/go

  gocd-agent:
    image: gocd/gocd-agent
    environment:
      - GO_SERVER=gocd-server
    links:
      - gocd-server
